// Statistical style analysis for Spanish text. No model call: every signal
// here is a measurable property of the text itself, which is what makes the
// result explainable and what makes it cost nothing per request.
//
// What this is NOT: a probability that a text was generated by AI. No
// technique available today produces a calibrated one, and the ones that
// claim to misfire on formal registers and on non-native writers. We report
// how strongly a text shows the patterns machine writing tends to have, and
// we name which patterns, so the reader can judge for themselves.

export type Band = "bajo" | "medio" | "alto";

export interface DetectorSignal {
  id: "uniformidad" | "conectores" | "repeticion" | "puntuacion";
  label: string;
  /** 0 = reads human, 1 = reads machine. */
  score: number;
  detail: string;
}

export interface DetectorResult {
  /** Weighted index, 0-100. Higher = more machine-like patterns. */
  index: number;
  band: Band;
  signals: DetectorSignal[];
  /** Per-sentence indices. Only produced for plans with sentenceHighlight. */
  sentences?: { text: string; score: number }[];
  words: number;
  sentenceCount: number;
  /**
   * False when the sample is too small for any of this to mean anything.
   * The caller must not show a band in that case.
   */
  reliable: boolean;
}

/** Below this the variance measures are noise, not signal. */
const MIN_WORDS = 120;
const MIN_SENTENCES = 5;

// Formulaic connectives and filler that Spanish-language models reach for far
// more often than people do. Written with their real spelling because they
// are shown back to the user; matching folds both sides, so accents and
// capitalisation in the input do not matter.
const FORMULAIC = [
  "en resumen",
  "en conclusión",
  "es importante destacar",
  "es importante señalar",
  "es importante mencionar",
  "cabe destacar",
  "cabe señalar",
  "cabe mencionar",
  "por otro lado",
  "por otra parte",
  "en este sentido",
  "de esta manera",
  "de este modo",
  "por lo tanto",
  "en definitiva",
  "en primer lugar",
  "en segundo lugar",
  "por último",
  "asimismo",
  "no obstante",
  "sin embargo",
  "además",
  "en la actualidad",
  "hoy en día",
  "a lo largo de",
  "juega un papel",
  "desempeña un papel",
  "es fundamental",
  "es esencial",
  "un aspecto clave",
  "en el mundo actual",
  "en el ámbito de",
  "profundizar en",
  "es crucial",
  "es vital",
];

/** Lowercase and strip diacritics so matching is not tripped by accents. */
function fold(text: string): string {
  return text.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "");
}

/**
 * Splits Spanish prose into sentences. Handles ¿?/¡! and the common
 * abbreviations that would otherwise cut a sentence in half.
 */
export function splitSentences(text: string): string[] {
  const guarded = text.replace(
    /\b(Sr|Sra|Srta|Dr|Dra|Ud|Uds|etc|pág|núm|art|vol|EE|UU|p\.\s?ej)\./gi,
    (m) => m.replace(".", "\u0000"),
  );
  return guarded
    .split(/(?<=[.!?…])[\s\n]+(?=[A-ZÁÉÍÓÚÑ¿¡"«(])|\n{2,}/)
    .map((s) => s.replace(/\u0000/g, ".").trim())
    .filter((s) => s.length > 0);
}

function words(text: string): string[] {
  return fold(text)
    .replace(/[^\p{L}\p{N}\s]/gu, " ")
    .split(/\s+/)
    .filter(Boolean);
}

/** Maps a raw measure onto 0-1, where `human` scores 0 and `machine` scores 1. */
function ramp(value: number, human: number, machine: number): number {
  const t = (value - human) / (machine - human);
  return Math.max(0, Math.min(1, t));
}

/**
 * Sentence-length variation ("burstiness"). People alternate long and short
 * sentences irregularly; generated prose tends to a flat rhythm. Measured as
 * the coefficient of variation, which is length-independent.
 */
function uniformity(sentences: string[]): DetectorSignal {
  const lengths = sentences.map((s) => words(s).length).filter((n) => n > 0);
  const mean = lengths.reduce((a, b) => a + b, 0) / lengths.length;
  const variance =
    lengths.reduce((acc, n) => acc + (n - mean) ** 2, 0) / lengths.length;
  const cv = mean > 0 ? Math.sqrt(variance) / mean : 0;

  return {
    id: "uniformidad",
    label: "Ritmo de las frases",
    // Human Spanish prose sits around 0.5-0.7; generated text clusters lower.
    score: ramp(cv, 0.6, 0.22),
    detail: `${
      cv < 0.35
        ? "Las frases varían poco de longitud"
        : cv < 0.5
          ? "Las frases varían de longitud algo menos de lo habitual"
          : "Las frases varían de longitud con naturalidad"
    } (coeficiente de variación ${cv.toFixed(2).replace(".", ",")}; en prosa humana suele rondar 0,60). Media de ${mean.toFixed(0)} palabras por frase.`,
  };
}

/** Density of formulaic connectives per 100 words. */
function connectors(text: string, wordCount: number): DetectorSignal {
  const folded = fold(text);
  let hits = 0;
  const found: string[] = [];
  for (const phrase of FORMULAIC) {
    const matches = folded.match(
      new RegExp(`\\b${fold(phrase).replace(/ /g, "\\s+")}\\b`, "g"),
    );
    if (matches) {
      hits += matches.length;
      found.push(phrase);
    }
  }
  const per100 = (hits / Math.max(wordCount, 1)) * 100;

  return {
    id: "conectores",
    label: "Conectores de relleno",
    score: ramp(per100, 0.3, 2.5),
    detail: hits
      ? `${hits} conector${hits === 1 ? "" : "es"} formulario${hits === 1 ? "" : "s"} en ${wordCount} palabras (${per100.toFixed(1)} por cada 100). Por ejemplo: «${found.slice(0, 3).join("», «")}».`
      : "No aparecen los conectores de relleno típicos de la escritura automática.",
  };
}

/** Repeated 3-grams and repeated sentence openings. */
function repetition(sentences: string[], allWords: string[]): DetectorSignal {
  const grams = new Map<string, number>();
  for (let i = 0; i + 2 < allWords.length; i++) {
    const key = allWords.slice(i, i + 3).join(" ");
    grams.set(key, (grams.get(key) ?? 0) + 1);
  }
  const repeatedGrams = [...grams.values()].filter((n) => n > 1).length;
  const gramRate = repeatedGrams / Math.max(grams.size, 1);

  const openings = new Map<string, number>();
  for (const s of sentences) {
    const first = words(s)[0];
    if (first) openings.set(first, (openings.get(first) ?? 0) + 1);
  }
  const repeatedOpenings = [...openings.values()].filter((n) => n > 1).length;
  const openingRate = repeatedOpenings / Math.max(openings.size, 1);

  const combined = gramRate * 0.5 + openingRate * 0.5;

  return {
    id: "repeticion",
    label: "Repetición de estructuras",
    score: ramp(combined, 0.05, 0.35),
    detail: `${repeatedGrams} secuencia${repeatedGrams === 1 ? "" : "s"} de tres palabras se repite${repeatedGrams === 1 ? "" : "n"}, y ${repeatedOpenings} palabra${repeatedOpenings === 1 ? "" : "s"} inicia${repeatedOpenings === 1 ? "" : "n"} más de una frase.`,
  };
}

/** Variety of punctuation. Generated Spanish leans on the comma and full stop. */
function punctuation(text: string, sentenceCount: number): DetectorSignal {
  const marks = [";", "—", "–", ":", "¿", "¡", "…", "(", '"', "«"];
  const used = marks.filter((m) => text.includes(m));
  const richCount = marks.reduce((acc, m) => acc + text.split(m).length - 1, 0);
  const perSentence = richCount / Math.max(sentenceCount, 1);

  return {
    id: "puntuacion",
    label: "Variedad de puntuación",
    // Softened on purpose: a formal register that simply favours commas
    // is not evidence of anything.
    score: ramp(perSentence, 0.6, 0.05),
    detail: used.length
      ? `Usa ${used.length} tipo${used.length === 1 ? "" : "s"} de puntuación más allá de la coma y el punto (${used.join(" ")}).`
      : "Solo aparecen comas y puntos: no hay punto y coma, guiones, dos puntos ni interrogaciones.",
  };
}

const WEIGHTS: Record<DetectorSignal["id"], number> = {
  uniformidad: 0.35,
  conectores: 0.3,
  repeticion: 0.2,
  puntuacion: 0.15,
};

/**
 * Band thresholds are deliberately asymmetric. Getting this wrong in one
 * direction misses some machine-written text; getting it wrong in the other
 * puts a false accusation on a student's desk. Those costs are not
 * comparable, so the bands are set to err toward "bajo": a careful human
 * academic text, the classic false positive, must not read as suspicious.
 */
export function bandFor(index: number): Band {
  if (index >= 75) return "alto";
  if (index >= 45) return "medio";
  return "bajo";
}

/**
 * Runs the analysis. `withSentences` is gated on the plan: the per-sentence
 * breakdown is a paid feature (PlanLimits.sentenceHighlight).
 */
export function analyze(
  text: string,
  { withSentences = false } = {},
): DetectorResult {
  const sentences = splitSentences(text);
  const allWords = words(text);
  const wordCount = allWords.length;

  const signals: DetectorSignal[] = [
    uniformity(sentences.length ? sentences : [text]),
    connectors(text, wordCount),
    repetition(sentences, allWords),
    punctuation(text, sentences.length),
  ];

  const index = Math.round(
    signals.reduce((acc, s) => acc + s.score * WEIGHTS[s.id], 0) * 100,
  );

  const reliable = wordCount >= MIN_WORDS && sentences.length >= MIN_SENTENCES;

  return {
    index,
    band: bandFor(index),
    signals,
    words: wordCount,
    sentenceCount: sentences.length,
    reliable,
    ...(withSentences && reliable
      ? {
          sentences: sentences.map((s) => {
            // Per sentence only the length-independent signals apply; the
            // rhythm measure needs several sentences to mean anything.
            const sw = words(s);
            const local = [
              connectors(s, sw.length),
              punctuation(s, 1),
            ] as DetectorSignal[];
            return {
              text: s,
              score: Math.round(
                ((local[0].score * 2 + local[1].score) / 3) * 100,
              ),
            };
          }),
        }
      : {}),
  };
}
